version: '3'

services:
  app:
    container_name: nextjs-dashboard
    build:
      context: .
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # # Set envrionment variables based on the .env file
    # env_file:
    #   - .env
    volumes:
      - ./app:/my-workdir/app  # Map the local 'app' directory to the '/my-workdir/app' directory in the container
      - ./public:/my-workdir/public  # Map the local 'public' directory to the '/my-workdir/public' directory in the container
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
