version: '3'

services:
  app:
    container_name: nextjs-dashboard
    build:
      context: .
      dockerfile: dev.Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - .env.local
    networks:
      - pg-network
    volumes:
      - ./app:/my-workdir/app  # Map the local 'app' directory to the '/my-workdir/app' directory in the container
      - ./public:/my-workdir/public  # Map the local 'public' directory to the '/my-workdir/public' directory in the container
    restart: always
    ports:
      - 3001:3001
networks:
  pg-network:
    external:
      name: postgres_pg-network